Models/Hall.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CinemaPlanet.Models
{
    public class Hall
    {
        [Key]
        [Required]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "ID must be between 1 to 50 letters")]
        public string ID{ get; set; }

        [Required]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Hall name must be between 2 to 50 letters")]
        public string HallName { get; set; }

        [Required]
        [Range(1, 32, ErrorMessage = "Please enter valid seats number in hall , seats range 1 to 32")]
        public int SeatsNumber { get; set; }

    }
}

Controllers/HallController.cs
using CinemaPlanet.Dal;
using CinemaPlanet.Models;
using CinemaPlanet.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CinemaPlanet.Controllers
{
    public class HallController : Controller
    {
        // GET: Hall
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddHall()
        {

            HallDal dal = new HallDal();
            HallViewModel vm = new HallViewModel();
            List<Hall> Halls = dal.Halls.ToList<Hall>();
            vm.Hall = new Hall();
            vm.Halls = Halls;
            return View(vm);
        }

        //[HttpPost]
        //public ActionResult Submit()
        //{
        //    MovieViewModel mvm = new MovieViewModel();
        //    Movie MyMovie = new Movie()
        //    {

        //        ID = int.Parse(Request.Form["Movie.ID"]).ToString(),
        //        mName = Request.Form["Movie.mName"],
        //        mDate = //DateTime.ParseExact(Request.Form["Movie.mDate"], @"MM/dd/yyyy hh:mm:ss", CultureInfo.InvariantCulture),
        //        DateTime.Parse(Request.Form["Movie.mDate"]),
        //        Price = int.Parse(Request.Form["Movie.Price"]),
        //        HallName = Request.Form["Movie.HallName"],
        //        Age = int.Parse(Request.Form["Movie.Age"]),
        //        Category = Request.Form["Movie.Category"],

        //    };

        //    MovieDal dal = new MovieDal();

        //    if (ModelState.IsValid)
        //    {

        //        dal.Movies.Add(MyMovie);
        //        dal.SaveChanges();
        //        mvm.Movie = new Movie();
        //    }


        //    else
        //    {
        //        mvm.Movie = MyMovie;
        //    }


        //    mvm.Movies = dal.Movies.ToList<Movie>();
        //    return View("EnterMovie", mvm);

        //}

        [HttpPost]
        public ActionResult SubmitHall()
        {
            HallViewModel vm = new HallViewModel();
            Hall MyHall = new Hall()
            {

                ID = Request.Form["Hall.ID"],
                HallName = Request.Form["Hall.HallName"],
                SeatsNumber = int.Parse(Request.Form["Hall.SeatsNumber"])

            };

            HallDal dal = new HallDal();

            if (ModelState.IsValid)
            {
                dal.Halls.Add(MyHall);
                dal.SaveChanges();
                vm.Hall = new Hall();
            }

            else
            {
                vm.Hall = MyHall;
            }

            vm.Halls = dal.Halls.ToList<Hall>();
            return View("AddHall", vm);

        }

        public ActionResult ChangeSeatsNumber()
        {
            HallViewModel vm = new HallViewModel();
            vm.Hall = new Hall();
            HallDal dal = new HallDal();
            string HallNameValue = Request.Form["txtHallName"];
            int _SeatsNumber = 0;

            if (Request.Form["HallSeatsNumber"] != null)
                _SeatsNumber = int.Parse(Request.Form["HallSeatsNumber"]);

            if (HallNameValue != null)
            {

                Hall addHall = dal.Halls.First(h => h.HallName == HallNameValue);
                addHall.SeatsNumber = _SeatsNumber;
                dal.SaveChanges();
                vm.Halls = dal.Halls.ToList<Hall>();
                return View(vm);

            }

            vm.Halls = dal.Halls.ToList<Hall>();
            return View(vm);
        }

        public bool MovieExist(string search)
        {
            HallDal dal = new HallDal();
            List<Hall> Halls = (from x in dal.Halls where x.HallName.Contains(search) select x).ToList<Hall>();

            if (Halls.Count >= 1)
                return true;

            return false;
        }

        //public ActionResult ChangePrice()
        //{
        //    MovieViewModel mvm = new MovieViewModel();
        //    mvm.Movie = new Movie();
        //    MovieDal dal = new MovieDal();
        //    string nameValue = Request.Form["txtMovieName"];
        //    int price = 0;

        //    if (Request.Form["MoviePrice"] != null)
        //        price = int.Parse(Request.Form["MoviePrice"]);

        //    if (MovieExist(nameValue))
        //    {
        //        Movie addMovie = dal.Movies.First(a => a.mName == nameValue);
        //        addMovie.Price = price;
        //        dal.SaveChanges();
        //        mvm.Movies = dal.Movies.ToList<Movie>();
        //        return View(mvm);
        //    }

        //    mvm.Movies = dal.Movies.ToList<Movie>();
        //    return View(mvm);

        //}
    }
}

Views/Hall/ChangeSeatsNumber.cshtml
@model CinemaPlanet.ViewModel.HallViewModel
@using CinemaPlanet.Models

@{
    ViewBag.Title = "ChangeSeatsNumber";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ChangeSeatsNumber</title>
</head>
<body>
    <div class="form-group">
        <form action="ChangeSeatsNumber" method="post">
            Enter hall name to update: <input id="Text1" name="txtHallName" type="text" class="form-control" />
            <br />
            Enter seats number: <input id="SeatsNumber" name="HallSeatsNumber" type="text" class="form-control" />
            <br />
            <input id="Submit2" type="submit" value="Update price" class="btn-group" />
        </form>

    </div>

    <table class=" table">
        <tr>
            <th>ID</th>
            <th>Hall Name</th>
            <th>Seats Number</th>


        </tr>

        @foreach (Hall Hall in Model.Halls)
        {
            <tr>
                <td>@Hall.ID</td>
                <td>@Hall.HallName</td>
                <td>@Hall.SeatsNumber</td>



            </tr>
        }
    </table>
</body>
</html>

Views/Hall/addHall.cshtml
@model CinemaPlanet.ViewModel.HallViewModel
@using CinemaPlanet.Models

@{
    ViewBag.Title = "AddHall";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title.</h2>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddHall</title>
</head>
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<body>
    @using (Html.BeginForm("SubmitHall", "Hall", FormMethod.Post))
    {
        <b>ID: </b> @Html.TextBoxFor(x => x.Hall.ID, new { @class = "form-control" }) @Html.ValidationMessageFor(x => x.Hall.ID)
        <br />
        <b>Hall Name: </b> @Html.TextBoxFor(x => x.Hall.HallName, new { @class = "form-control" }) @Html.ValidationMessageFor(x => x.Hall.HallName)
        <br />
        <b>Seats Number: </b> @Html.TextBoxFor(x => x.Hall.SeatsNumber, new { @class = "form-control" }) @Html.ValidationMessageFor(x => x.Hall.SeatsNumber)
        <br />
        <input id="Submit1" type="submit" value="Add Hall" class="btn-group" />
        <br />
    }

    <table class=" table">
        <tr>
            <th>ID</th>
            <th>Hall Name</th>
            <th>Seats Number</th>
           

        </tr>

        @foreach (Hall Hall in Model.Halls)
        {
            <tr>
                <td>@Hall.ID</td>
                <td>@Hall.HallName</td>
                <td>@Hall.SeatsNumber</td>
                


            </tr>
        }
    </table>

    <div>
    </div>
</body>
</html>